# Enable SPI
CONFIG_SPI=y

# Enable GPIO
CONFIG_GPIO=y

# Enable logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# Enable necessary kernel features
CONFIG_MAIN_STACK_SIZE=4096

# Console and UART for logging
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y

# Disable Bluetooth if not needed
CONFIG_BT=n

# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# Enable the driver
#CONFIG_NRF24L01=y

CONFIG_ESP32_USE_UNSUPPORTED_REVISION=y